### PR TITLE
Add hungarian language translation

### PR DESCRIPTION
**Pull request by takraj**

### CODE REVIEW

**Comment by michaelarnauts** [comment]
Thanks @takraj ! Out of curiosity, with what add-on are you using IPTV Manager?

**Comment by takraj** [comment]
> Thanks @takraj ! Out of curiosity, with what add-on are you using IPTV Manager?

@michaelarnauts There is an addon that lets you to watch hungarian public IPTV channels. I have created a patch for it, to integrate with your addon, so one can now watch these channels on the normal Live TV interface of Kodi.

**Comment by michaelarnauts** [comment]
> > Thanks @takraj ! Out of curiosity, with what add-on are you using IPTV Manager?
> 
> @michaelarnauts There is an addon that lets you to watch hungarian public IPTV channels. I have created a patch for it, to integrate with your addon, so one can now watch these channels on the normal Live TV interface of Kodi.

Cool, feel free to share information about this add-on so we can add this to the wiki: https://github.com/add-ons/service.iptv.manager/wiki/Supported-Addons

**Comment by takraj** [comment]
> 
> 
> > > Thanks @takraj ! Out of curiosity, with what add-on are you using IPTV Manager?
> > 
> > 
> > @michaelarnauts There is an addon that lets you to watch hungarian public IPTV channels. I have created a patch for it, to integrate with your addon, so one can now watch these channels on the normal Live TV interface of Kodi.
> 
> Cool, feel free to share information about this add-on so we can add this to the wiki: https://github.com/add-ons/service.iptv.manager/wiki/Supported-Addons

My pull request is still pending, but here is the link: https://github.com/OStreamH/repository.onlinestream/pull/2

The reposiotry is actually a Kodi repository hosting this one addon only. The addon itself is called 'Online Stream'. There is no VOD, it provides only Live TV and Live Radio. The web service behind it is https://onlinestream.live

It's free to use, and the addon was originally created by @OStreamH and @aky01

**Comment by michaelarnauts** [comment]
Cool. It's nice to see that IPTV Manager is getting in use outside our own (Belgian) Add-ons! Thanks!

**Pull request merged**
