### PR TITLE
Remove python 2.7 / Leia support

### PR DESCRIPTION
**Pull request by peno64**

### CODE REVIEW

**Comment by peno64** [comment]
@michaelarnauts 

I get these errors on all tests:


-----------------------------------
Your code has been rated at 9.40/10

make: *** [Makefile:28: check-pylint] Error 28
Error: Process completed with exit code 1.

Any idea why this is because I don't see it.

**Comment by michaelarnauts** [comment]
Try adding consider-using-f-string to the .pylintrc file

**Comment by michaelarnauts** [comment]
You can open the details on the tests, pylint is to verify the actual code and code style. Sometimes new rules are added that you can implement or ignore. I would ignore them for now.

There are also tests that run the actual code to make sure it works. Those run when the checks are done.

**Comment by peno64** [comment]
@michaelarnauts 

I would like to push the changes to the standard kodi repo but I get the following error:

git push origin matrix
remote: Permission to xbmc/repo-scripts.git denied to peno64.
fatal: unable to access 'https://github.com/xbmc/repo-scripts.git/': The requested URL returned error: 403

Do I not have the permissions to do this?
At https://kodi.wiki/view/Submitting_Add-ons I read: "Only PRs from the add-on author or his successor will be accepted. Patches should be submitted upstream to the original author first."
Is this the issue?

**Comment by michaelarnauts** [comment]
You'll need to push to your own fork, and make a merge request for that. There is a script in my other repos (in the scripts folder. I think it's named deploy.py) that does this.

I think I'll need to comment on the PR to indicate that you are the successor :)

**Comment by peno64** [comment]
But if I pull the changes done on https://github.com/add-ons/service.iptv.manager/ back into my branch, how then can I create a PR again to https://github.com/add-ons/service.iptv.manager because there will be no changes.

**Pull request merged**
