### PR TITLE
Add a release workflow

### PR DESCRIPTION
**Pull request by dagwieers**
This PR adds a GitHub CI workflow to push to the official Kodi
repositories.

### CODE REVIEW

**Comment by dagwieers** [comment]
After adding the required secrets we can automatically push to the official repository.

**Comment by dagwieers** [comment]
This will be useful to #47

**Comment by michaelarnauts** [comment]
Is there a difference between the GH_TOKEN and GITHUB_TOKEN vars?

**Comment by dagwieers** [comment]
Yes, GITHUB_TOKEN is automatically set by GitHub.
GH_TOKEN is a personal token you need to generate to perform actions in your name.

**Comment by dagwieers** [comment]
Closing this.

**Comment by michaelarnauts** [comment]
We can still do this when we get a sense of how much Kodi likes the way IPTV Manager works. I'll reopen this, so we don't forget about this.

**Pull request merged**
